"""add itineraries tables

Revision ID: 3e9e19912d63
Revises: eb6056da5e16
Create Date: 2026-01-28 11:32:02.106472

"""
from typing import Sequence, Union



# revision identifiers, used by Alembic.
revision: str = '3e9e19912d63'
down_revision: Union[str, None] = 'eb6056da5e16'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
